### ISSUE TITLE
Object version

### ISSUE THREAD

**Issue by Alex293** [soberman/ARSLineProgress#10]
I know static version of the design make it easy to use but it lake adaptability. I saw you made some fun to draw it on a particular view. I'd like to use it this way but on multiple views (images loadings in collection). I need a separate start/stop/update loader for each cell. Is there a way to use your lib for what i want, are you interested if I try to adapt your class to instance code or just look for another lib ?

**Comment by Alex293** [comment]
Great design tho :)

**Comment by soberman** [comment]
Hey Alex,
Thank you :) Actually, I was thinking about adapting these "spinning wheels" for other parts, for instance for loading images in collectionViews, just as you've said. And actually, I was planning to do it this weekend. So I would suggest you to wait for it, since it is coming either way ;)

**Comment by Alex293** [comment]
Awesome news ! I'll be glad to give you some feedback!

**Comment by soberman** [comment]
Hey Alex,

didn't make it this weekend, though I have made a better structure by separating the components to a different files for better navigation and understanding the whole structure. I suppose it should be even further refactored :/
Anyways, in case you can't wait - feel free to PR the finished version on case you have already made one. I will probable try to find time for it next weekend.

**Comment by soberman** [comment]
Hey Alex,
can't make it this weekend. Don't know when I have time for it.
You are welcome to make a PR in case you want.
