### ISSUE TITLE
Question: Background color

### ISSUE THREAD

**Issue by timbroder** [soberman/ARSLineProgress#12]
What is the best way to change the background color of the spinner?

Thanks!

**Comment by soberman** [comment]
Hey!

I use UIVisualEffectView so there you can basically change it from dark to light one. But in case you need custom one - feel free to for the project and suit it to your needs.

**Comment by soberman** [comment]
Actually there is open PR that should bring this functionality, so stay tuned.

**Comment by timbroder** [comment]
@soberman thanks!
