### ISSUE TITLE
Location of ARSLineProgress view

### ISSUE THREAD

**Issue by sarfrazb** [soberman/ARSLineProgress#14]
Hi

You've made a super beautiful activity indicator!
I've been having some issues with its location, however.

To give some context:
Upon selection of a cell in a UITableViewController, we segue to a UIWebView taking up the entirety of the screen. All of my ViewControllers are embedded in a UINavigationController.

So if I type, for example:
`ARSLineProgress.show()`
two things occur:
1. It appears in the middle of the screen, but only in its initial orientation - changing orientation skews the location of the ARSLineProgress.
2. It blocks the UI; I cannot click the back button for example.

If I type:
`ARSLineProgress.showOnView(showDoc)` //showDoc is the name of the UIWebView
two things occur:
1. It no longer blocks the UI!
2. It also no longer appears in the centre of the screen :(

Have you encountered anything like this yet?
If you're able to offer any advice, it would be greatly appreciated.

Either way, I thought I would provide this feedback, as well as thank you for everything you've done on this project thus far - it's really wonderful :)

Cheers
Saf

**Comment by sarfrazb** [comment]
**This is scenario 1 (where it blocks the UI)**

Here it is in the initial orientation:
<img width="1136" alt="screen shot 2016-10-17 at 12 47 29 am" src="https://cloud.githubusercontent.com/assets/13691330/19417870/567515e0-9403-11e6-8c5a-e7ae2433aba7.png">

Here it is once the orientation has been changed:
<img width="880" alt="screen shot 2016-10-17 at 12 47 33 am" src="https://cloud.githubusercontent.com/assets/13691330/19417871/5cd80fd2-9403-11e6-9c10-81a5e118bb04.png">

**Comment by soberman** [comment]
Hey!

Thank you :)
First of all - none of the methods block the UI as I intentionally leave it up to a developer to do it.
As for the positioning problem - I do remember that during development there was this issue but I fixed it, at least it worked fine on iOS9. Looks like behaviour changed in iOS10.

Anyways, I have fixed this issue, feel free to pull updates.
