### ISSUE TITLE
Not showing up in v1.2.1

### ISSUE THREAD

**Issue by NSMyself** [soberman/ARSLineProgress#17]
I tried importing ARSLineProgress version 1.2.1 (essentially, the last commit before migrating to Swift 3) both manually and via Carthage but the spinner isn't showing up. Not even in the debug view hierarchy.

I did notice it runs in the demo project, so I assume it's something related with my project, although I essentially copied and pasted your call to `showWithPresentCompetionBlock`  to my rather blank initial screen and still nothing happened (the prints do appear, though).

I know this is a bit vague and old (especially because ARSLineProgress has since moved to Swift 3) but I decided to open this issue because I saw another issue (closed) mentioning this very problem.

**Comment by soberman** [comment]
Hey,

as in the closed issue - I tried reproducing this bug but couldn't, everything worked fine for me in the blank project, so I closed the issue.
Share a link to the repo of your project where it doesn't work so I could take a look at the issue.

**Comment by NSMyself** [comment]
My bad, got it. 

I was setting up the window object in the AppDelegate inside `didFinishLaunchingWithOptions` because initially I wasn't using storyboards at all, but I am now.

This causes the spinner not to show up in my project:
`self.window = UIWindow.init(frame: UIScreen.mainScreen().bounds)`

I cleaned it up and it's working nicely now.

Full method here btw:

```
func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {

            self.window = UIWindow.init(frame: UIScreen.mainScreen().bounds)

            let storyboardId = (UIApplication.isFirstLaunch()) ? "Authentication" : "Routing"
            let storyboard:UIStoryboard = UIStoryboard.init(name: storyboardId, bundle: nil)
            let initialVC = storyboard.instantiateInitialViewController()

            self.window?.rootViewController = initialVC
            self.window?.makeKeyAndVisible()

            return true
        }
```

Sorry. Thanks for your time
