### ISSUE TITLE
Xcode 8.1 and Swift 3.0

### ISSUE THREAD

**Issue by gateway** [soberman/ARSLineProgress#18]
Hi, we had to finally update to Xcode 8.1 from 7.3.1 which now we are facing a big pain in dealing with the pods we are using and the fact that some of them are not updated for the proper syntax.

Here is what Im seeing so far..

![image](https://cloud.githubusercontent.com/assets/519563/19875829/5d3ee1d6-9f8d-11e6-9a7d-7f0fb71c3c17.png)

Any ideas how to get around this.. we prefer to migrate all to 3, and not 2.3 for our project.

**Comment by soberman** [comment]
Hi!

I have migrated ARSLineProgress to Swift 3 a month ago, make sure to get the fresh version!

Cheeers

**Comment by gateway** [comment]
Sorry to re-open this but right now with Xcode 8.1 we are using your framework and the pod file..

Here is our podfile

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
target "AppA" do
    pod 'Parse'
    pod 'ParseFacebookUtilsV4'
    pod 'FBAnnotationClusteringSwift'
    pod 'ARSLineProgress', '~> 2.0'
    pod 'Bolts'
    pod 'HMSegmentedControl'
    pod 'MXSegmentedPager'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.0'
      end
    end
  end
end

```

We still have a bunch of errors and its not working properly, so either the pod file is not the latest or something from xcode 8.0 to 8.1 changed.. 

We are just letting you know!

**Comment by DanSessions** [comment]
I'm also seeing this issue. It looks as though there are some missing file references in the Carthage project. I've created #19 that should fix it.

**Comment by gateway** [comment]
@DanSessions would this be propagated over to pods as well? and thanks btw

**Comment by DanSessions** [comment]
Checked this again and it doesn't appear as though our issues were related, sorry. I tried your Podfile and I only get errors related to the FBAnnotationClusteringSwift pod. Could this be a CocoaPods caching issue?

**Comment by gateway** [comment]
@DanSessions doesnt see to be, I nuked my Pods folder and did pod install which should get all the latest.. are you running xcode 8.1?

**Comment by DanSessions** [comment]
Yes, I'm running Xcode 8.1.

Try running `sudo rm -fr ~/Library/Caches/CocoaPods/`.
