### ISSUE TITLE
BackgroundView user interaction 

### ISSUE THREAD

**Issue by tvstuff** [soberman/ARSLineProgress#2]
currently if we show progress bar , background view still has user interaction
is there any way to disable that?

**Comment by soberman** [comment]
Disabling user interaction is not a good idea by Apple's guidelines. But in case you really need it - you can always do it yourself via `view.userInteractionEnabled = false`.

**Comment by Urkman** [comment]
Why not add a background view and blur it...
So the view can't be accessed?

**Comment by soberman** [comment]
It is not advised by the Apple Human Interface Guidelines to block UI.
In case your particular case requires it - you can achieve it on your side.
