### ISSUE TITLE
How to use in Objective c?

### ISSUE THREAD

**Issue by bintu1234** [soberman/ARSLineProgress#20]
Hi it was looking great, is there any plan for objective c?.

**Comment by soberman** [comment]
Hi, thanks!
You can use the generated Objective-C bridging interface that is going to be generated automatically when you add it into your project.

**Comment by bintu1234** [comment]
Thanks, is it working in xcode 7.3.1?

**Comment by soberman** [comment]
Sure thing. No problems.

**Comment by soberman** [comment]
But it depends on which version you choose - the most recent one uses Swift 3, so it won't work in Xcode 7.3.1. Choose older ones in case you have to use it in Xcode 7.3.1.
