### ISSUE TITLE
Xcode 8.3 Warnings from Podfile

### ISSUE THREAD

**Issue by gateway** [soberman/ARSLineProgress#24]
Apple recently pushed out Xcode 8.3, today while building our app after updating we are getting a bunch of warnings and I thought I would make you guys aware of this.

![image](https://cloud.githubusercontent.com/assets/519563/24726732/3d77548c-1a08-11e7-8958-8901de114fca.png)

**Comment by soberman** [comment]
Thank you! I have removed all warnings.
