### ISSUE TITLE
Background Color of the Progress View

### ISSUE THREAD

**Issue by utkueray** [soberman/ARSLineProgress#29]
Can someone help me with my little problem. It's not technically a issue. I couldn't find how to change the background color of the progress circle. I want to make the black square disappear. How can I set the alpha of that to 0 ? Or is there an other way to solve this problem.

Thank you for sparing time.

**Comment by ikliuchko** [comment]
@utkueray probably setting
ARSLineProgressConfiguration.backgroundViewStyle = .full
or
ARSLineProgressConfiguration.backgroundViewStyle = .simple
will do the thing?
