### ISSUE TITLE
OC version

### ISSUE THREAD

**Issue by Easyzhan** [soberman/ARSLineProgress#3]
i need OC version,have?

**Comment by soberman** [comment]
What is it?

**Comment by Easyzhan** [comment]
Have you plan to code an Objective-C version of this 😃?

**Comment by soberman** [comment]
No. There is no need for this, just configure your project to use Swift files and you are good to go.

**Comment by Easyzhan** [comment]
yep,but xcode7.3.1prompt function has a problem,sometimes it does't have the auto-suggest capab.

**Comment by soberman** [comment]
well, that is not the reason to rewrite it in Objective-C :)
