### ISSUE TITLE
ARSLineProgress broken for Swift 4.2

### ISSUE THREAD

**Issue by githubautomator** [soberman/ARSLineProgress#31]
is there a newer version?

**Comment by soberman** [comment]
Not yet, though I will make one. In case you have a working PR already - feel free to send one over.

**Comment by hemangshah** [comment]
+1

**Comment by hemangshah** [comment]
Submitted: https://github.com/soberman/ARSLineProgress/pull/32

**Comment by lamprosg** [comment]
Is this in the 3.0.0 release? I don't seem to get the changes,

**Comment by soberman** [comment]
Yes it is. Are you using Cocoapods?

**Comment by githubautomator** [comment]
Indeed.

Am 01.11.2018 um 00:36 schrieb Yarik Arsenkin <notifications@github.com<mailto:notifications@github.com>>:


Yes it is. Are you using Cocoapods?

**Comment by soberman** [comment]
The please make sure that the version format you have specified in the `Podfile` allows you to upgrade to major versions. Most likely not in case you don't have any updates.
You can update your `Podfile` with the following format: `pod 'ARSLineProgress', '~> 3.0'`

**Comment by githubautomator** [comment]
Tony for the hint - wilco.

**Comment by lamprosg** [comment]
My project for some reason had swift version 4. So that is why I was seeing errors.
