### ISSUE TITLE
Not able to hide ARSLineProgress in iOS 15

### ISSUE THREAD

**Issue by Mujtabaulhasankhan** [soberman/ARSLineProgress#35]
I am not able to hide ARSLineProgress in iOS 15. It is working fine in iOS 14.3 and below version.

ARSLineProgress.hide()

I am using this code to hide ARSLineProgress. 

 public static func hide() {
        ars_hideLoader(ars_currentLoader, withCompletionBlock: nil)
    }

@soberman Please check

**Comment by Mujtabaulhasankhan** [comment]
hide not working in iOS 15 my issue is not fix @soberman

**Comment by soberman** [comment]
@Mujtabaulhasankhan Feel free to open a PR with a fix 👍

**Comment by burf2000** [comment]
@Mujtabaulhasankhan did you manage to fix this?

**Comment by burf2000** [comment]
Someone has done a fix (CATransaction.commit()), please @soberman can you merge it in and create a new pod

**Comment by soberman** [comment]
Done.
