### ISSUE TITLE
Can you give me some sample code in how to implement this into my project ? 

### ISSUE THREAD

**Issue by JohnWhisker** [soberman/ARSLineProgress#4]
I'm new to Swift and I don't know how to use this. I've already installed it using cocoapod but I don't know where to put ARSLineProgress.show(). I put it in my ViewController but it didn't work.

**Comment by soberman** [comment]
Hey @JohnWhisker,
it doesn't really matter where you call it, as the call will be forwarded to the main queue and the loader will be placed on top of the `window`'s `view`. So far you are doing it properly. There might be something with your code maybe.

**Comment by soberman** [comment]
You can call this method from Objective-C as well, it will look like this:
`[ARSLineProgress show];`

**Comment by JohnWhisker** [comment]
I did call but it didn't work. I call ARSLineProgress.show() for testing in viewDidLoad() method right after super.viewDidLoad() but nothing show up

**Comment by soberman** [comment]
I don't know what you are doing, but I've just created a sample project and imported ARSLineProgress and called `show()` from `viewDidLoad` and it worked. Debug your code, I suppose :)

``` Swift
override func viewDidLoad() {
    super.viewDidLoad()

    ARSLineProgress.show()
}
```
