### ISSUE TITLE
support swift 3 ?

### ISSUE THREAD

**Issue by 5SMNOONMS5** [soberman/ARSLineProgress#6]
I just install **Xocde8 beta6**  

but it occur lot of error like below 
![screen shot 2016-09-07 at 12 08 36 pm 2](https://cloud.githubusercontent.com/assets/8379901/18299482/e5bd52d2-74f3-11e6-99e1-c2a6a29af6c1.png)

are you going to update the code to support swift 3 ?

**Comment by soberman** [comment]
Hey Stephen,
yes, sure, I am going to update it to Swift 3 as soon as we have Xcode 8 GM.
